function initForm(urlParams){

    console.log("initing form", urlParams);
    var desiredStartDate = new Date(2003, 1,1); 
    if(urlParams.has("start")){
        desiredStartDate = new Date(urlParams.get("start"));
        console.log("amk",$('input[name="start"]'));
        $('input[name="start"]').val(urlParams.get("start"));
        urlParams.delete('start');
    } else {
        desiredStartDate = new Date(2003, 1,1);
    }

    var TLMiktar = 100;
    if(urlParams.has("miktar")){
        TLMiktar = parseFloat(urlParams.get("miktar"));
        urlParams.delete('miktar');
        $("#miktar").attr('value', TLMiktar);
    }

    var DevletKatkisiFonu ;
    if(urlParams.has("devlet")){
        DevletKatkisiFonu = urlParams.get("devlet");
        urlParams.delete('devlet');
        $("#devlet").attr('value', DevletKatkisiFonu);
    }

    if(urlParams.has("inflationAdj")){
        var inflationAdj = urlParams.get("inflationAdj") == 'on';
        urlParams.delete('inflationAdj');
        $("#inflationAdj").prop('checked', inflationAdj);
    }

    
    var c=0;
    for(var kv of urlParams.entries()){
        addFon(kv[0], kv[1], c==0);
        c += 1;
    }

    if (c==0){
        addFon('','', true);
    }
    
    $("#devlet-fon").insertAfter(fonlar);

}

function tarihAciklama(graphData){
    graphData.dateAligment.then( function(x)  {
        if (x.reason != '') {
            console.log("algiment reason", x.reason);
            $("#tarih-aciklama").removeClass("invisible").addClass("visible");
            $("#fon-neden").text(x.reason);
            $("#fon-tarih").text(x.date.toLocaleDateString("tr-TR"));
    }});
}

function duzelt(){
    $(".fon").each(function(i, elem){
        //console.log(elem);
        var kod = $(elem).find(".fonadi").first().val();
        var agirlik = $(elem).find(".fonoran").first().val();
        $(elem).find(".fonkodu").first().attr("name", kod);
        $(elem).find(".fonkodu").first().attr("value", agirlik);
    });
}

function addFon(kod, agirlik, ilk = false){
    const labelClass = ilk ? "col-form-label" : "sr-only";
    const aciklamaKodHtml = `<small  class="form-text text-muted"> BES Fonu. Yazmaya baslayin ve listeden fonunuzu secin. Fon kodusunuz gozukecektir </small>`;
    const aciklamaOranHtml = `<small  class="form-text text-muted"> Bu fon porftyounuzude ne kadar oradan olsun. Degerler normalize edilecektir </small>`;
    const aciklamaKod =  "";
    const aciklamaOran =  "";
    const gozuksun = ilk ? "hidden" : "visible"
    const delButton = `
            <button type="button" onclick='$(this).closest(".form-row").remove();' class="btn btn-outline-primary" >Sil</button>
    `;

    const delHtml = ilk ? "" : delButton
    
    $("#fons").append(`
        <div class="form-row fon">

        <div class="form-group col-9">
        <label for="fon" class="${labelClass}">BES Fonu</label>
        ${aciklamaKod}
          <input type="list" class="fonadi form-control" list="fonlarimiz" value="${kod}">
           ${fonlar}
          <input type="hidden" class="fonkodu">
        </div>

       <div class="form-group col-2">

         <label for="fonoran" class="${labelClass}">For Orani</label>
         ${aciklamaOran}
        <input type="number" class="fonoran form-control" value="${agirlik}">
        </div>

        <div class="form-group col-1" visibility=${gozuksun}>

        ${delHtml}
       </div>


    </div>

    `);
    
}



const fonlar = `
 <datalist id="fonlarimiz">
<option value="ANG" label="AEGON  EMEKLİLİK VE HAYAT A.Ş. STANDART EMEKLİLİK YATIRIM FONU"> AEGON  EMEKLİLİK VE HAYAT A.Ş. STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="AEY" label="AEGON EMEKLILIK VE HAYAT A.Ş. KATKI EMEKLİLİK YATIRIM FONU"> AEGON EMEKLILIK VE HAYAT A.Ş. KATKI EMEKLİLİK YATIRIM FONU </option> 
<option value="ANS" label="AEGON EMEKLİLİK VE HAYAT  A.Ş. HİSSE SENEDİ EMEKLİLİK YATIRIM FONU"> AEGON EMEKLİLİK VE HAYAT  A.Ş. HİSSE SENEDİ EMEKLİLİK YATIRIM FONU </option> 
<option value="ANE" label="AEGON EMEKLİLİK VE HAYAT A.Ş. KARMA EMEKLİLİK YATIRIM FONU"> AEGON EMEKLİLİK VE HAYAT A.Ş. KARMA EMEKLİLİK YATIRIM FONU </option> 
<option value="ANK" label="AEGON EMEKLİLİK VE HAYAT A.Ş. PARA PİYASASI EMEKLİLİK YATIRIM FONU"> AEGON EMEKLİLİK VE HAYAT A.Ş. PARA PİYASASI EMEKLİLİK YATIRIM FONU </option> 
<option value="AEE" label="ALLIANZ HAYAT VE EMEKLILIK A.Ş. DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> ALLIANZ HAYAT VE EMEKLILIK A.Ş. DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="AZK" label="ALLIANZ HAYAT VE EMEKLİLİK A.Ş. BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"> ALLIANZ HAYAT VE EMEKLİLİK A.Ş. BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU </option> 
<option value="AZA" label="ALLIANZ HAYAT VE EMEKLİLİK A.Ş. BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU"> ALLIANZ HAYAT VE EMEKLİLİK A.Ş. BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="AZD" label="ALLIANZ HAYAT VE EMEKLİLİK A.Ş. BİRİNCİ KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"> ALLIANZ HAYAT VE EMEKLİLİK A.Ş. BİRİNCİ KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU </option> 
<option value="AZB" label="ALLIANZ HAYAT VE EMEKLİLİK A.Ş. DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> ALLIANZ HAYAT VE EMEKLİLİK A.Ş. DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="AZY" label="ALLIANZ HAYAT VE EMEKLİLİK A.Ş. DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU"> ALLIANZ HAYAT VE EMEKLİLİK A.Ş. DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="AZE" label="ALLIANZ HAYAT VE EMEKLİLİK A.Ş. EMANET PARA PİYASASI EMEKLİLİK YATIRIM FONU"> ALLIANZ HAYAT VE EMEKLİLİK A.Ş. EMANET PARA PİYASASI EMEKLİLİK YATIRIM FONU </option> 
<option value="AZH" label="ALLIANZ HAYAT VE EMEKLİLİK A.Ş. HİSSE SENEDİ EMEKLİLİK YATIRIM  FONU"> ALLIANZ HAYAT VE EMEKLİLİK A.Ş. HİSSE SENEDİ EMEKLİLİK YATIRIM  FONU </option> 
<option value="AZM" label="ALLIANZ HAYAT VE EMEKLİLİK A.Ş. KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"> ALLIANZ HAYAT VE EMEKLİLİK A.Ş. KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU </option> 
<option value="AZO" label="ALLIANZ HAYAT VE EMEKLİLİK A.Ş. KARMA EMEKLİLİK YATIRIM FONU"> ALLIANZ HAYAT VE EMEKLİLİK A.Ş. KARMA EMEKLİLİK YATIRIM FONU </option> 
<option value="AZL" label="ALLIANZ HAYAT VE EMEKLİLİK A.Ş. PARA PİYASASI EMEKLİLİK YATIRIM FONU"> ALLIANZ HAYAT VE EMEKLİLİK A.Ş. PARA PİYASASI EMEKLİLİK YATIRIM FONU </option> 
<option value="AUG" label="ALLIANZ HAYAT VE EMEKLİLİK A.Ş. İKİNCİ KAMU DIŞ BORÇLANMA ARAÇLARI EMEKİLİK YATIRIM FONU"> ALLIANZ HAYAT VE EMEKLİLİK A.Ş. İKİNCİ KAMU DIŞ BORÇLANMA ARAÇLARI EMEKİLİK YATIRIM FONU </option> 
<option value="AZT" label="ALLIANZ HAYAT VE EMEKLİLİK A.Ş.KATKI EMEKLİLİK YATIRIM FONU"> ALLIANZ HAYAT VE EMEKLİLİK A.Ş.KATKI EMEKLİLİK YATIRIM FONU </option> 
<option value="ACV" label="ALLIANZ YAŞAM VE EMEKLILIK A.Ş. BAŞLANGIÇ KATILIM EMEKLILIK YATIRIM FONU"> ALLIANZ YAŞAM VE EMEKLILIK A.Ş. BAŞLANGIÇ KATILIM EMEKLILIK YATIRIM FONU </option> 
<option value="ANJ" label="ALLIANZ YAŞAM VE EMEKLILIK A.Ş. OKS DENGELİ DEĞIŞKEN EMEKLILIK YATIRIM FONU"> ALLIANZ YAŞAM VE EMEKLILIK A.Ş. OKS DENGELİ DEĞIŞKEN EMEKLILIK YATIRIM FONU </option> 
<option value="AFJ" label="ALLIANZ YAŞAM VE EMEKLILIK A.Ş. OKS TEMKINLI DEĞIŞKEN EMEKLILIK YATIRIM FONU"> ALLIANZ YAŞAM VE EMEKLILIK A.Ş. OKS TEMKINLI DEĞIŞKEN EMEKLILIK YATIRIM FONU </option> 
<option value="APG" label="ALLIANZ YAŞAM VE EMEKLILIK A.Ş. SÜRDÜRÜLEBILIRLIK HISSE SENEDI EMEKLILIK YATıRıM FONU"> ALLIANZ YAŞAM VE EMEKLILIK A.Ş. SÜRDÜRÜLEBILIRLIK HISSE SENEDI EMEKLILIK YATıRıM FONU </option> 
<option value="ALH" label="ALLIANZ YAŞAM VE EMEKLİLİK A.Ş.  HİSSE SENEDİ EMEKLİLİK YATIRIM FONU"> ALLIANZ YAŞAM VE EMEKLİLİK A.Ş.  HİSSE SENEDİ EMEKLİLİK YATIRIM FONU </option> 
<option value="AUA" label="ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. 2035 HEDEF FON SEPETİ EMEKLİLİK YATIRIM FONU"> ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. 2035 HEDEF FON SEPETİ EMEKLİLİK YATIRIM FONU </option> 
<option value="AMZ" label="ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. ALTIN EMEKLİLİK YATIRIM FONU"> ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. ALTIN EMEKLİLİK YATIRIM FONU </option> 
<option value="AEO" label="ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. ATA FİNANS DENGELİ DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU"> ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. ATA FİNANS DENGELİ DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="AEZ" label="ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. ATA FİNANS DİNAMİK DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU"> ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. ATA FİNANS DİNAMİK DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="AMH" label="ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. ATAK DEĞIŞKEN GRUP EMEKLİLİK YAT.FONU"> ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. ATAK DEĞIŞKEN GRUP EMEKLİLİK YAT.FONU </option> 
<option value="AEU" label="ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. BIST TEMETTÜ ENDEKSİ EMEKLİLİK YATIRIM FONU"> ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. BIST TEMETTÜ ENDEKSİ EMEKLİLİK YATIRIM FONU </option> 
<option value="AMA" label="ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"> ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU </option> 
<option value="AMG" label="ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. BİRİNCİ KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM  FONU"> ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. BİRİNCİ KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM  FONU </option> 
<option value="ALS" label="ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. DENGELİ DEĞİKEN EMEKLİLİK YATIRIM FONU"> ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. DENGELİ DEĞİKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="AGL" label="ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. DENGELİ DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU"> ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. DENGELİ DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="ALU" label="ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="ALL" label="ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. EMANET PARA PİYASASI EMEKLİLİK YATIRIM FONU"> ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. EMANET PARA PİYASASI EMEKLİLİK YATIRIM FONU </option> 
<option value="ALR" label="ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. KARMA EMEKLİLİK YATIRIM FONU"> ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. KARMA EMEKLİLİK YATIRIM FONU </option> 
<option value="AMY" label="ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. KARMA GRUP EMEKLİLİK YATIRIM FONU"> ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. KARMA GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="AMF" label="ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. KATKI EMEKLİLİK YATIRIM FONU"> ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. KATKI EMEKLİLİK YATIRIM FONU </option> 
<option value="AMP" label="ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. PARA PİYASASI EMEKLİLİK YATIRIM FONU"> ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. PARA PİYASASI EMEKLİLİK YATIRIM FONU </option> 
<option value="AMS" label="ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. STANDART EMEKLİLİK YATIRIM FONU"> ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="AEN" label="ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="AEP" label="ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. UNİLEVER DİNAMİK DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU"> ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. UNİLEVER DİNAMİK DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="AMR" label="ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. İKİNCİ KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"> ALLIANZ YAŞAM VE EMEKLİLİK A.Ş. İKİNCİ KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU </option> 
<option value="AMB" label="ALLIANZ YAŞAM VE EMEKLİLİK A.Ş.BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU"> ALLIANZ YAŞAM VE EMEKLİLİK A.Ş.BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="ALI" label="ALLIANZ YAŞAM VE EMEKLİLİK A.Ş.KOÇ İŞTİRAK ENDEKSİ EMEKLİLİK YATIRIM FONU"> ALLIANZ YAŞAM VE EMEKLİLİK A.Ş.KOÇ İŞTİRAK ENDEKSİ EMEKLİLİK YATIRIM FONU </option> 
<option value="AIP" label="ALLIANZ YAŞAM VE EMEKLİLİK A.Ş.OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> ALLIANZ YAŞAM VE EMEKLİLİK A.Ş.OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="AIE" label="ALLIANZ YAŞAM VE EMEKLİLİK A.Ş.OKS BÜYÜME KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> ALLIANZ YAŞAM VE EMEKLİLİK A.Ş.OKS BÜYÜME KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="AMN" label="ALLIANZ YAŞAM VE EMEKLİLİK A.Ş.TEMKINLI DEĞIŞKEN GRUP EMEKLİLİK YATIRIM FONU"> ALLIANZ YAŞAM VE EMEKLİLİK A.Ş.TEMKINLI DEĞIŞKEN GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="AEC" label="ALLIANZ YAŞAM VE EMEKLİLİK A.Ş.UNİLEVER DENGELİ DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU"> ALLIANZ YAŞAM VE EMEKLİLİK A.Ş.UNİLEVER DENGELİ DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="AZN" label="ALLİANZ HAYAT VE EMEKLİLİK A.Ş. ALTIN EMEKLİLİK YATIRIM FONU"> ALLİANZ HAYAT VE EMEKLİLİK A.Ş. ALTIN EMEKLİLİK YATIRIM FONU </option> 
<option value="AZS" label="ALLİANZ HAYAT VE EMEKLİLİK A.Ş. STANDART EMEKLİLİK YATIRIM FONU"> ALLİANZ HAYAT VE EMEKLİLİK A.Ş. STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="ALZ" label="ALLİANZ YAŞAM VE EMEKLİLİK A.Ş. BAŞLANGIÇ EMEKLİLİK YATIRIM FONU"> ALLİANZ YAŞAM VE EMEKLİLİK A.Ş. BAŞLANGIÇ EMEKLİLİK YATIRIM FONU </option> 
<option value="FYY" label="ALLİANZ YAŞAM VE EMEKLİLİK A.Ş. KATILIM KATKI EMEKLİLİK YATIRIM FONU"> ALLİANZ YAŞAM VE EMEKLİLİK A.Ş. KATILIM KATKI EMEKLİLİK YATIRIM FONU </option> 
<option value="FYU" label="ALLİANZ YAŞAM VE EMEKLİLİK A.Ş. KATILIM STANDART EMEKLİLİK YATIRIM FONU"> ALLİANZ YAŞAM VE EMEKLİLİK A.Ş. KATILIM STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="KOE" label="ALLİANZ YAŞAM VE EMEKLİLİK A.Ş. KOÇ HOLDİNG EMEKLİ VAKFI BİRİNCİ DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU"> ALLİANZ YAŞAM VE EMEKLİLİK A.Ş. KOÇ HOLDİNG EMEKLİ VAKFI BİRİNCİ DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="KOS" label="ALLİANZ YAŞAM VE EMEKLİLİK A.Ş. OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU"> ALLİANZ YAŞAM VE EMEKLİLİK A.Ş. OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="KOA" label="ALLİANZ YAŞAM VE EMEKLİLİK A.Ş. OKS STANDART EMEKLİLİK YATIRIM FONU"> ALLİANZ YAŞAM VE EMEKLİLİK A.Ş. OKS STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="ALJ" label="ALLİANZ YAŞAM VE EMEKLİLİK A.Ş.OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> ALLİANZ YAŞAM VE EMEKLİLİK A.Ş.OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="ANP" label="ALLİANZ YAŞAM VE EMEKLİLİK A.Ş.OKS DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> ALLİANZ YAŞAM VE EMEKLİLİK A.Ş.OKS DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="AJA" label="ANADOLU HAYAT  EMEKLİLİK A.Ş. OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> ANADOLU HAYAT  EMEKLİLİK A.Ş. OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="AJG" label="ANADOLU HAYAT  EMEKLİLİK A.Ş. OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> ANADOLU HAYAT  EMEKLİLİK A.Ş. OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="AJB" label="ANADOLU HAYAT  EMEKLİLİK A.Ş. OKS ATAK DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> ANADOLU HAYAT  EMEKLİLİK A.Ş. OKS ATAK DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="" label="ANADOLU HAYAT  EMEKLİLİK A.Ş. OKS ATAK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> ANADOLU HAYAT  EMEKLİLİK A.Ş. OKS ATAK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="AJC" label="ANADOLU HAYAT  EMEKLİLİK A.Ş. OKS DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> ANADOLU HAYAT  EMEKLİLİK A.Ş. OKS DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="AJF" label="ANADOLU HAYAT  EMEKLİLİK A.Ş. OKS TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> ANADOLU HAYAT  EMEKLİLİK A.Ş. OKS TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="AEA" label="ANADOLU HAYAT A.Ş. ALTIN KATILIM EMEKLİLİK YAT.FONU"> ANADOLU HAYAT A.Ş. ALTIN KATILIM EMEKLİLİK YAT.FONU </option> 
<option value="ABE" label="ANADOLU HAYAT EMEKLILIK A.Ş.B.R.I.C.ÜLKELER YABANCI DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> ANADOLU HAYAT EMEKLILIK A.Ş.B.R.I.C.ÜLKELER YABANCI DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="HS1" label="ANADOLU HAYAT EMEKLİLİK  A.Ş. BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"> ANADOLU HAYAT EMEKLİLİK  A.Ş. BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU </option> 
<option value="AHL" label="ANADOLU HAYAT EMEKLİLİK A.Ş. AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> ANADOLU HAYAT EMEKLİLİK A.Ş. AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="AH0" label="ANADOLU HAYAT EMEKLİLİK A.Ş. ATAK DEĞİŞKEN  EMEKLİLİK YATIRIM FONU"> ANADOLU HAYAT EMEKLİLİK A.Ş. ATAK DEĞİŞKEN  EMEKLİLİK YATIRIM FONU </option> 
<option value="AH6" label="ANADOLU HAYAT EMEKLİLİK A.Ş. BİRİNCİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> ANADOLU HAYAT EMEKLİLİK A.Ş. BİRİNCİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="AH2" label="ANADOLU HAYAT EMEKLİLİK A.Ş. PARA PİYASASI EMEKLİLİK YATIRIM FONU"> ANADOLU HAYAT EMEKLİLİK A.Ş. PARA PİYASASI EMEKLİLİK YATIRIM FONU </option> 
<option value="ATK" label="ANADOLU HAYAT EMEKLİLİK A.Ş. STANDART EMEKLİLİK YAT.FONU"> ANADOLU HAYAT EMEKLİLİK A.Ş. STANDART EMEKLİLİK YAT.FONU </option> 
<option value="AH8" label="ANADOLU HAYAT EMEKLİLİK A.Ş. TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> ANADOLU HAYAT EMEKLİLİK A.Ş. TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="AHC" label="ANADOLU HAYAT EMEKLİLİK A.Ş. ÖZEL SEKTÖR BORÇLANMA ARAÇLARI E.Y.F"> ANADOLU HAYAT EMEKLİLİK A.Ş. ÖZEL SEKTÖR BORÇLANMA ARAÇLARI E.Y.F </option> 
<option value="AH1" label="ANADOLU HAYAT EMEKLİLİK A.Ş. İKİNCİ BORÇLANMA ARAÇLARI EMEKLILIK YATIRIM FONU"> ANADOLU HAYAT EMEKLİLİK A.Ş. İKİNCİ BORÇLANMA ARAÇLARI EMEKLILIK YATIRIM FONU </option> 
<option value="AG2" label="ANADOLU HAYAT EMEKLİLİK A.Ş.BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU"> ANADOLU HAYAT EMEKLİLİK A.Ş.BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="AH3" label="ANADOLU HAYAT EMEKLİLİK A.Ş.BİRİNCİ KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"> ANADOLU HAYAT EMEKLİLİK A.Ş.BİRİNCİ KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU </option> 
<option value="AH9" label="ANADOLU HAYAT EMEKLİLİK A.Ş.DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> ANADOLU HAYAT EMEKLİLİK A.Ş.DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="AH5" label="ANADOLU HAYAT EMEKLİLİK A.Ş.HİSSE SENEDİ EMEKLİLİK YATIRIM FONU"> ANADOLU HAYAT EMEKLİLİK A.Ş.HİSSE SENEDİ EMEKLİLİK YATIRIM FONU </option> 
<option value="AG3" label="ANADOLU HAYAT EMEKLİLİK A.Ş.HİSSE SENEDİ GRUP EMEKLİLİK YATIRIM FONU"> ANADOLU HAYAT EMEKLİLİK A.Ş.HİSSE SENEDİ GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="AER" label="ANADOLU HAYAT EMEKLİLİK A.Ş.KATILIM KATKI EMEK.Y.F"> ANADOLU HAYAT EMEKLİLİK A.Ş.KATILIM KATKI EMEK.Y.F </option> 
<option value="AGE" label="ANADOLU HAYAT EMEKLİLİK A.Ş.KATILIM STANDART EMEKLİLİK YATIRIM FONU"> ANADOLU HAYAT EMEKLİLİK A.Ş.KATILIM STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="AFH" label="ANADOLU HAYAT EMEKLİLİK A.Ş.OKS STANDART EMEKLİLİK YATIRIM FONU"> ANADOLU HAYAT EMEKLİLİK A.Ş.OKS STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="AG4" label="ANADOLU HAYAT EMEKLİLİK A.Ş.TEMKİNLİ DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU"> ANADOLU HAYAT EMEKLİLİK A.Ş.TEMKİNLİ DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="AHB" label="ANADOLU HAYAT EMEKLİLİK A.Ş.İKİNCİ HİSSE SENEDİ EMEKLİLİK YATIRIM FONU"> ANADOLU HAYAT EMEKLİLİK A.Ş.İKİNCİ HİSSE SENEDİ EMEKLİLİK YATIRIM FONU </option> 
<option value="AH4" label="ANADOLU HAYAT EMEKLİLİK A.Ş.İKİNCİ KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"> ANADOLU HAYAT EMEKLİLİK A.Ş.İKİNCİ KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU </option> 
<option value="ATE" label="ANADOLU HAYAT EMEKLİLİK A.Ş.İŞ BANKASI İŞTİRAK ENDEKSİ EMEKLİLİK YATIRIM FONU"> ANADOLU HAYAT EMEKLİLİK A.Ş.İŞ BANKASI İŞTİRAK ENDEKSİ EMEKLİLİK YATIRIM FONU </option> 
<option value="AET" label="ANADOLU HAYAT EMEKLİLİK KATKI EMEK.YAT.FONU"> ANADOLU HAYAT EMEKLİLİK KATKI EMEK.YAT.FONU </option> 
<option value="AG1" label="ANADOLU HAYAT EMEKİLİK A.Ş. İKİNCİ BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU"> ANADOLU HAYAT EMEKİLİK A.Ş. İKİNCİ BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="AO1" label="ANADOLU HAYAT VE EMEKLİLİK A.Ş. BAŞLANGIÇ EMEKLİLİK YATIRIM FONU"> ANADOLU HAYAT VE EMEKLİLİK A.Ş. BAŞLANGIÇ EMEKLİLİK YATIRIM FONU </option> 
<option value="AO2" label="ANADOLU HAYAT VE EMEKLİLİK A.Ş. BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU"> ANADOLU HAYAT VE EMEKLİLİK A.Ş. BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU </option> 
<option value="AFP" label="ANADOLU HAYAT VE EMEKLİLİK A.Ş. OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU"> ANADOLU HAYAT VE EMEKLİLİK A.Ş. OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="AE2" label="AVİVASA EMEKLİLİK VE HAYAT  A.Ş. BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"> AVİVASA EMEKLİLİK VE HAYAT  A.Ş. BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU </option> 
<option value="AHJ" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş. BAŞLANGIÇ EMEKLİLİK YATIRIM FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş. BAŞLANGIÇ EMEKLİLİK YATIRIM FONU </option> 
<option value="AEK" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş. BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş. BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="AVR" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş. BRIC ÜLKELERİ YABANCI DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş. BRIC ÜLKELERİ YABANCI DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="AE4" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş. BİRİNCİ DEĞİŞKEN EMEKLİLİK YAT.FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş. BİRİNCİ DEĞİŞKEN EMEKLİLİK YAT.FONU </option> 
<option value="AE1" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş. BİRİNCİ PARA PİYASASI EMEKLİLİK YATIRIM FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş. BİRİNCİ PARA PİYASASI EMEKLİLİK YATIRIM FONU </option> 
<option value="AVP" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş. DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş. DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="AE3" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş. DİNAMİK DEĞİŞKEN  EMEKLİLİK YATIRIM FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş. DİNAMİK DEĞİŞKEN  EMEKLİLİK YATIRIM FONU </option> 
<option value="AEB" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş. HİSSE SENEDİ GRUP EMEKLİLİK YATIRIM FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş. HİSSE SENEDİ GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="AVG" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş. KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş. KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU </option> 
<option value="AVY" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş. KARMA  GRUP EMEKLİLİK YATIRIM FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş. KARMA  GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="AEI" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş. KATKI EMEKLİLİK YATIRIM FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş. KATKI EMEKLİLİK YATIRIM FONU </option> 
<option value="AEG" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş. MUHAFAZAKAR DEĞİŞKEN  EMEKLİLİK YATIRIM FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş. MUHAFAZAKAR DEĞİŞKEN  EMEKLİLİK YATIRIM FONU </option> 
<option value="VVA" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş. OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş. OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="VVZ" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş. OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş. OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="VVE" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş. OKS DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş. OKS DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="VVD" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş. OKS DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş. OKS DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="VVU" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş. OKS DİNAMİK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş. OKS DİNAMİK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="VVM" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş. OKS MUHAFAZAKAR DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş. OKS MUHAFAZAKAR DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="AAJ" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş. OKS STANDART EMEKLİLİK YATIRIM FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş. OKS STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="AVN" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş. STANDART EMEKLİLİK YATIRIM FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş. STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="AVK" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş. UZUN VADELİ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş. UZUN VADELİ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU </option> 
<option value="AVB" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş. UZUN VADELİ KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş. UZUN VADELİ KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU </option> 
<option value="AVO" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş. ÖZEL SEKTÖR BORÇLANMA ARAÇLARI EMEK.YAT.FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş. ÖZEL SEKTÖR BORÇLANMA ARAÇLARI EMEK.YAT.FONU </option> 
<option value="AVE" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş.AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş.AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="AEL" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş.ALTIN EMEKLİLİK YAT.FON"> AVİVASA EMEKLİLİK VE HAYAT A.Ş.ALTIN EMEKLİLİK YAT.FON </option> 
<option value="AVJ" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş.BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş.BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU </option> 
<option value="AEH" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş.HİSSE SENEDİ EMEKLİLİK YATIRIM FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş.HİSSE SENEDİ EMEKLİLİK YATIRIM FONU </option> 
<option value="AVD" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş.KARMA EMEKLİLİK YATIRIM FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş.KARMA EMEKLİLİK YATIRIM FONU </option> 
<option value="FYL" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş.KATILIM KATKI EMEKLİLİK YATIRIM FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş.KATILIM KATKI EMEKLİLİK YATIRIM FONU </option> 
<option value="FYN" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş.KATILIM STANDART EMEKLİLİK YATIRIM FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş.KATILIM STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="AYJ" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş.OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş.OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="AVH" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş.TEMETTÜ ÖDEYEN  ŞİRKETLER HİSSE SENEDİ EMEKLİLİK YATIRIM FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş.TEMETTÜ ÖDEYEN  ŞİRKETLER HİSSE SENEDİ EMEKLİLİK YATIRIM FONU </option> 
<option value="AVU" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş.İKİNCİ DEĞİŞKEN  EMEKLİLİK YAT.FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş.İKİNCİ DEĞİŞKEN  EMEKLİLİK YAT.FONU </option> 
<option value="AVL" label="AVİVASA EMEKLİLİK VE HAYAT A.Ş.İKİNCİ PARA PİYASASI EMEKLİLİK YATIRIM FONU"> AVİVASA EMEKLİLİK VE HAYAT A.Ş.İKİNCİ PARA PİYASASI EMEKLİLİK YATIRIM FONU </option> 
<option value="HEA" label="AXA HAYAT VE EMEKLİLİK A.Ş. ALTIN KATILIM EMEKLİLİK YATIRIM FONU"> AXA HAYAT VE EMEKLİLİK A.Ş. ALTIN KATILIM EMEKLİLİK YATIRIM FONU </option> 
<option value="HEL" label="AXA HAYAT VE EMEKLİLİK A.Ş. BAŞLANGIÇ EMEKLİLİK YATIRIM FONU"> AXA HAYAT VE EMEKLİLİK A.Ş. BAŞLANGIÇ EMEKLİLİK YATIRIM FONU </option> 
<option value="HEG" label="AXA HAYAT VE EMEKLİLİK A.Ş. BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU"> AXA HAYAT VE EMEKLİLİK A.Ş. BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU </option> 
<option value="HES" label="AXA HAYAT VE EMEKLİLİK A.Ş. HİSSE SENEDİ EMEKLİLİK YATIRIM FONU"> AXA HAYAT VE EMEKLİLİK A.Ş. HİSSE SENEDİ EMEKLİLİK YATIRIM FONU </option> 
<option value="HEK" label="AXA HAYAT VE EMEKLİLİK A.Ş. KAMU BORÇLANMA ARAÇLARI  STANDART  EMEK.YAT.FONU"> AXA HAYAT VE EMEKLİLİK A.Ş. KAMU BORÇLANMA ARAÇLARI  STANDART  EMEK.YAT.FONU </option> 
<option value="HEE" label="AXA HAYAT VE EMEKLİLİK A.Ş. KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> AXA HAYAT VE EMEKLİLİK A.Ş. KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="HER" label="AXA HAYAT VE EMEKLİLİK A.Ş. KATILIM KATKI EMEKLİLİK YATIRIM FONU"> AXA HAYAT VE EMEKLİLİK A.Ş. KATILIM KATKI EMEKLİLİK YATIRIM FONU </option> 
<option value="HET" label="AXA HAYAT VE EMEKLİLİK A.Ş. KATKI EMEKLİLİK YATIRIM FONU"> AXA HAYAT VE EMEKLİLİK A.Ş. KATKI EMEKLİLİK YATIRIM FONU </option> 
<option value="AJR" label="AXA HAYAT VE EMEKLİLİK A.Ş. OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> AXA HAYAT VE EMEKLİLİK A.Ş. OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="AJZ" label="AXA HAYAT VE EMEKLİLİK A.Ş. OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> AXA HAYAT VE EMEKLİLİK A.Ş. OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="AJP" label="AXA HAYAT VE EMEKLİLİK A.Ş. OKS ATAK DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> AXA HAYAT VE EMEKLİLİK A.Ş. OKS ATAK DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="AJY" label="AXA HAYAT VE EMEKLİLİK A.Ş. OKS ATAK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> AXA HAYAT VE EMEKLİLİK A.Ş. OKS ATAK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="AJV" label="AXA HAYAT VE EMEKLİLİK A.Ş. OKS DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> AXA HAYAT VE EMEKLİLİK A.Ş. OKS DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="HEI" label="AXA HAYAT VE EMEKLİLİK A.Ş. OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU"> AXA HAYAT VE EMEKLİLİK A.Ş. OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="HEC" label="AXA HAYAT VE EMEKLİLİK A.Ş. OKS STANDART EMEKLİLİK YATIRIM FONU"> AXA HAYAT VE EMEKLİLİK A.Ş. OKS STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="AJT" label="AXA HAYAT VE EMEKLİLİK A.Ş. OKS TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> AXA HAYAT VE EMEKLİLİK A.Ş. OKS TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="HEB" label="AXA HAYAT VE EMEKLİLİK A.Ş.DEĞİŞKEN  EMEKLİLİK YATIRIM FONU"> AXA HAYAT VE EMEKLİLİK A.Ş.DEĞİŞKEN  EMEKLİLİK YATIRIM FONU </option> 
<option value="HEP" label="AXA HAYAT VE EMEKLİLİK A.Ş.PARA PİYASASI  EMEKLİLİK YATIRIM FONU"> AXA HAYAT VE EMEKLİLİK A.Ş.PARA PİYASASI  EMEKLİLİK YATIRIM FONU </option> 
<option value="HED" label="AXA HAYAT VE EMKLİLİK A.Ş.KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"> AXA HAYAT VE EMKLİLİK A.Ş.KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU </option> 
<option value="TKV" label="BEREKET  EMEKLİLİK VE HAYAT A.Ş. BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU"> BEREKET  EMEKLİLİK VE HAYAT A.Ş. BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU </option> 
<option value="AGA" label="BEREKET EMEKLİLİK VE HAYAT A.Ş. ALTIN KATILIM EMEKLİLİK YAT.FONU"> BEREKET EMEKLİLİK VE HAYAT A.Ş. ALTIN KATILIM EMEKLİLİK YAT.FONU </option> 
<option value="AGB" label="BEREKET EMEKLİLİK VE HAYAT A.Ş. BÜYÜME KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> BEREKET EMEKLİLİK VE HAYAT A.Ş. BÜYÜME KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="AGG" label="BEREKET EMEKLİLİK VE HAYAT A.Ş. KATILIM DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU"> BEREKET EMEKLİLİK VE HAYAT A.Ş. KATILIM DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="AGH" label="BEREKET EMEKLİLİK VE HAYAT A.Ş. KATILIM HİSSE SENEDİ EMEKLİLİK YATIRIM FONU"> BEREKET EMEKLİLİK VE HAYAT A.Ş. KATILIM HİSSE SENEDİ EMEKLİLİK YATIRIM FONU </option> 
<option value="AGT" label="BEREKET EMEKLİLİK VE HAYAT A.Ş. KATILIM KATKI EMEKLİLİK YATIRIM FONU"> BEREKET EMEKLİLİK VE HAYAT A.Ş. KATILIM KATKI EMEKLİLİK YATIRIM FONU </option> 
<option value="AGD" label="BEREKET EMEKLİLİK VE HAYAT A.Ş. KATILIM STANDART EMEKLİLİK YATIRIM FONU"> BEREKET EMEKLİLİK VE HAYAT A.Ş. KATILIM STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="AGM" label="BEREKET EMEKLİLİK VE HAYAT A.Ş. MUHAFAZAKAR KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> BEREKET EMEKLİLİK VE HAYAT A.Ş. MUHAFAZAKAR KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="BEI" label="BEREKET EMEKLİLİK VE HAYAT A.Ş. OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU"> BEREKET EMEKLİLİK VE HAYAT A.Ş. OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="BEO" label="BEREKET EMEKLİLİK VE HAYAT A.Ş.OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> BEREKET EMEKLİLİK VE HAYAT A.Ş.OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="BEF" label="BEREKET EMEKLİLİK VE HAYAT A.Ş.OKS DİNAMİK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> BEREKET EMEKLİLİK VE HAYAT A.Ş.OKS DİNAMİK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="BPE" label="BNP PARİBAS CARDİF EMEKLİLİK  A.Ş. BİRİNCİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> BNP PARİBAS CARDİF EMEKLİLİK  A.Ş. BİRİNCİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="BPU" label="BNP PARİBAS CARDİF EMEKLİLİK  A.Ş. BİRİNCİ KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"> BNP PARİBAS CARDİF EMEKLİLİK  A.Ş. BİRİNCİ KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU </option> 
<option value="BPH" label="BNP PARİBAS CARDİF EMEKLİLİK  A.Ş. HİSSE SENEDİ EMEKLİLİK YATIRIM FONU"> BNP PARİBAS CARDİF EMEKLİLİK  A.Ş. HİSSE SENEDİ EMEKLİLİK YATIRIM FONU </option> 
<option value="PRC" label="BNP PARİBAS CARDİF EMEKLİLİK A.Ş. BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU"> BNP PARİBAS CARDİF EMEKLİLİK A.Ş. BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU </option> 
<option value="BPL" label="BNP PARİBAS CARDİF EMEKLİLİK A.Ş. BİRİNCİ PARA PİYASASI EMEKLİLİK YATIRIM FONU"> BNP PARİBAS CARDİF EMEKLİLİK A.Ş. BİRİNCİ PARA PİYASASI EMEKLİLİK YATIRIM FONU </option> 
<option value="BNY" label="BNP PARİBAS CARDİF EMEKLİLİK A.Ş. DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU"> BNP PARİBAS CARDİF EMEKLİLİK A.Ş. DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="BPM" label="BNP PARİBAS CARDİF EMEKLİLİK A.Ş. EMANET PARA PİYASASI EMEKLİLİK YATIRIM FONU"> BNP PARİBAS CARDİF EMEKLİLİK A.Ş. EMANET PARA PİYASASI EMEKLİLİK YATIRIM FONU </option> 
<option value="BPG" label="BNP PARİBAS CARDİF EMEKLİLİK A.Ş. KAMU BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"> BNP PARİBAS CARDİF EMEKLİLİK A.Ş. KAMU BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU </option> 
<option value="BPF" label="BNP PARİBAS CARDİF EMEKLİLİK A.Ş. KAMU BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU"> BNP PARİBAS CARDİF EMEKLİLİK A.Ş. KAMU BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="BNK" label="BNP PARİBAS CARDİF EMEKLİLİK A.Ş. KATKI EMEKLİLİK YATIRIM FONU"> BNP PARİBAS CARDİF EMEKLİLİK A.Ş. KATKI EMEKLİLİK YATIRIM FONU </option> 
<option value="BPI" label="BNP PARİBAS CARDİF EMEKLİLİK A.Ş. OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> BNP PARİBAS CARDİF EMEKLİLİK A.Ş. OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="BPS" label="BNP PARİBAS CARDİF EMEKLİLİK A.Ş. OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> BNP PARİBAS CARDİF EMEKLİLİK A.Ş. OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="BPJ" label="BNP PARİBAS CARDİF EMEKLİLİK A.Ş. OKS DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> BNP PARİBAS CARDİF EMEKLİLİK A.Ş. OKS DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="BPN" label="BNP PARİBAS CARDİF EMEKLİLİK A.Ş. OKS DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> BNP PARİBAS CARDİF EMEKLİLİK A.Ş. OKS DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="BPO" label="BNP PARİBAS CARDİF EMEKLİLİK A.Ş. OKS DİNAMİK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> BNP PARİBAS CARDİF EMEKLİLİK A.Ş. OKS DİNAMİK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="BPK" label="BNP PARİBAS CARDİF EMEKLİLİK A.Ş. İKİNCİ KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"> BNP PARİBAS CARDİF EMEKLİLİK A.Ş. İKİNCİ KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU </option> 
<option value="PRS" label="BNP PARİBAS CARDİF EMEKLİLİK A.Ş.BAŞLANGIÇ EMEKLİLİK YATIRIM FONU"> BNP PARİBAS CARDİF EMEKLİLİK A.Ş.BAŞLANGIÇ EMEKLİLİK YATIRIM FONU </option> 
<option value="BNZ" label="BNP PARİBAS CARDİF EMEKLİLİK A.Ş.OKS KATILIM  STANDART EMEKLİLİK  YATIRIM FONU"> BNP PARİBAS CARDİF EMEKLİLİK A.Ş.OKS KATILIM  STANDART EMEKLİLİK  YATIRIM FONU </option> 
<option value="BPR" label="BNP PARİBAS CARDİF EMEKLİLİK A.Ş.OKS MUHAFAZAKAR DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> BNP PARİBAS CARDİF EMEKLİLİK A.Ş.OKS MUHAFAZAKAR DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="BNL" label="BNP PARİBAS CARDİF EMEKLİLİK A.Ş.OKS STANDART EMEKLİLİK  YATIRIM FONU"> BNP PARİBAS CARDİF EMEKLİLİK A.Ş.OKS STANDART EMEKLİLİK  YATIRIM FONU </option> 
<option value="BNS" label="BNP PARİBAS CARDİF EMEKLİLİK A.Ş.STANDART EMEKLİLİK YAT.FONU"> BNP PARİBAS CARDİF EMEKLİLİK A.Ş.STANDART EMEKLİLİK YAT.FONU </option> 
<option value="BNB" label="BNP PARİBAS CARDİF EMEKLİLİK A.Ş.İKİNCİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> BNP PARİBAS CARDİF EMEKLİLİK A.Ş.İKİNCİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="BNA" label="BNP PARİBAS CARDİF EMEKLİLİK ALTIN EMEKLİLİK YATIRIM  FONU"> BNP PARİBAS CARDİF EMEKLİLİK ALTIN EMEKLİLİK YATIRIM  FONU </option> 
<option value="CGG" label="CİGNA FINANS EMEKLILIK VE HAYAT A.Ş. KAMU BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU"> CİGNA FINANS EMEKLILIK VE HAYAT A.Ş. KAMU BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="CHN" label="CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş. BİRİNCİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş. BİRİNCİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="CGE" label="CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş. BİRİNCİ DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU"> CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş. BİRİNCİ DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="CHH" label="CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş. BİRİNCİ HİSSE SENEDİ EMEKLİLİK YATIRIM FONU"> CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş. BİRİNCİ HİSSE SENEDİ EMEKLİLİK YATIRIM FONU </option> 
<option value="CHK" label="CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş. KAMU BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"> CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş. KAMU BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU </option> 
<option value="CFK" label="CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş. KATILIM KATKI EMEKLİLİK YATIRIM FONU"> CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş. KATILIM KATKI EMEKLİLİK YATIRIM FONU </option> 
<option value="CHT" label="CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş. KATKI E.Y.F"> CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş. KATKI E.Y.F </option> 
<option value="CFE" label="CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş. OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU"> CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş. OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="CHU" label="CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş. OKS STANDART EMEKLİLİK YATIRIM FONU"> CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş. OKS STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="CHL" label="CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş. PARA PİYASASI EMEKLİLİK YATIRIM FONU"> CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş. PARA PİYASASI EMEKLİLİK YATIRIM FONU </option> 
<option value="CHS" label="CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş. STANDART E.Y.F"> CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş. STANDART E.Y.F </option> 
<option value="CHM" label="CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş. İKİNCİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş. İKİNCİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="CFB" label="CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş.BAŞLANGIÇ EMEKLİLİK YATIRIM FONU"> CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş.BAŞLANGIÇ EMEKLİLİK YATIRIM FONU </option> 
<option value="CFY" label="CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş.BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU"> CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş.BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU </option> 
<option value="CHG" label="CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş.OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş.OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="CHD" label="CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş.OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş.OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="CHO" label="CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş.OKS ATAK DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş.OKS ATAK DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="CHA" label="CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş.OKS DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş.OKS DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="CHI" label="CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş.OKS DİNAMİK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş.OKS DİNAMİK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="CHC" label="CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş.OKS MUHAFAZAKAR DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> CİGNA FİNANS EMEKLİLİK VE HAYAT A.Ş.OKS MUHAFAZAKAR DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="EST" label="FİBA EMEKLILIK VE HAYAT A.Ş. OYAK PORTFÖY STANDART EMEKLİLİK YATIRIM FONU"> FİBA EMEKLILIK VE HAYAT A.Ş. OYAK PORTFÖY STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="EIE" label="FİBA EMEKLİLİK A.Ş. VE HAYAT A.Ş. İKİNCİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK A.Ş. VE HAYAT A.Ş. İKİNCİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="GRA" label="FİBA EMEKLİLİK VE HAYAT A.Ş. ALTIN EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş. ALTIN EMEKLİLİK YATIRIM FONU </option> 
<option value="FEA" label="FİBA EMEKLİLİK VE HAYAT A.Ş. ATLAS PORTFÖY DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş. ATLAS PORTFÖY DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="EIG" label="FİBA EMEKLİLİK VE HAYAT A.Ş. BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş. BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU </option> 
<option value="BGK" label="FİBA EMEKLİLİK VE HAYAT A.Ş. BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş. BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="FES" label="FİBA EMEKLİLİK VE HAYAT A.Ş. BİRİNCİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş. BİRİNCİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="BGE" label="FİBA EMEKLİLİK VE HAYAT A.Ş. DENGELİ DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş. DENGELİ DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="FER" label="FİBA EMEKLİLİK VE HAYAT A.Ş. DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş. DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="FEV" label="FİBA EMEKLİLİK VE HAYAT A.Ş. GLOBAL MD PORTFÖY DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş. GLOBAL MD PORTFÖY DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="EIK" label="FİBA EMEKLİLİK VE HAYAT A.Ş. KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş. KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU </option> 
<option value="BKB" label="FİBA EMEKLİLİK VE HAYAT A.Ş. KAMU DIŞ BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş. KAMU DIŞ BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="FIS" label="FİBA EMEKLİLİK VE HAYAT A.Ş. KATILIM STANDART EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş. KATILIM STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="FEI" label="FİBA EMEKLİLİK VE HAYAT A.Ş. KATKI EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş. KATKI EMEKLİLİK YATIRIM FONU </option> 
<option value="FIC" label="FİBA EMEKLİLİK VE HAYAT A.Ş. OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş. OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="FGF" label="FİBA EMEKLİLİK VE HAYAT A.Ş. OKS STANDART EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş. OKS STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="FIR" label="FİBA EMEKLİLİK VE HAYAT A.Ş. OSMANLI PORTFÖY DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş. OSMANLI PORTFÖY DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="EHG" label="FİBA EMEKLİLİK VE HAYAT A.Ş. OYAK PORTFÖY DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş. OYAK PORTFÖY DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="EIH" label="FİBA EMEKLİLİK VE HAYAT A.Ş. OYAK PORTFÖY HİSSE SENEDİ EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş. OYAK PORTFÖY HİSSE SENEDİ EMEKLİLİK YATIRIM FONU </option> 
<option value="EIF" label="FİBA EMEKLİLİK VE HAYAT A.Ş. OYAK PORTFÖY KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş. OYAK PORTFÖY KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU </option> 
<option value="FET" label="FİBA EMEKLİLİK VE HAYAT A.Ş. PARA PİYASASI EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş. PARA PİYASASI EMEKLİLİK YATIRIM FONU </option> 
<option value="FEZ" label="FİBA EMEKLİLİK VE HAYAT A.Ş. PERFORM PORTFÖY DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş. PERFORM PORTFÖY DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="FEO" label="FİBA EMEKLİLİK VE HAYAT A.Ş. QİNVEST PORTFÖY DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş. QİNVEST PORTFÖY DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="FEN" label="FİBA EMEKLİLİK VE HAYAT A.Ş. STANDART EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş. STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="FEF" label="FİBA EMEKLİLİK VE HAYAT A.Ş. TACİRLER PORTFÖY DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş. TACİRLER PORTFÖY DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="FIF" label="FİBA EMEKLİLİK VE HAYAT A.Ş. İSTANBUL PORTFÖY DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş. İSTANBUL PORTFÖY DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="FIE" label="FİBA EMEKLİLİK VE HAYAT A.Ş.BAŞLANGIÇ EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş.BAŞLANGIÇ EMEKLİLİK YATIRIM FONU </option> 
<option value="FIY" label="FİBA EMEKLİLİK VE HAYAT A.Ş.BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM A.Ş."> FİBA EMEKLİLİK VE HAYAT A.Ş.BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM A.Ş. </option> 
<option value="BEE" label="FİBA EMEKLİLİK VE HAYAT A.Ş.DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş.DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="BEK" label="FİBA EMEKLİLİK VE HAYAT A.Ş.FİBA BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş.FİBA BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU </option> 
<option value="BEH" label="FİBA EMEKLİLİK VE HAYAT A.Ş.HİSSE SENEDİ EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş.HİSSE SENEDİ EMEKLİLİK YATIRIM FONU </option> 
<option value="BBH" label="FİBA EMEKLİLİK VE HAYAT A.Ş.HİSSE SENEDİ GRUP EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş.HİSSE SENEDİ GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="FIK" label="FİBA EMEKLİLİK VE HAYAT A.Ş.KARE PORTFÖY FON SEPETİ EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş.KARE PORTFÖY FON SEPETİ EMEKLİLİK YATIRIM FONU </option> 
<option value="FII" label="FİBA EMEKLİLİK VE HAYAT A.Ş.KATILIM KATKI EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş.KATILIM KATKI EMEKLİLİK YATIRIM FONU </option> 
<option value="FIM" label="FİBA EMEKLİLİK VE HAYAT A.Ş.MÜKAFAT PORTFÖY KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş.MÜKAFAT PORTFÖY KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="FIU" label="FİBA EMEKLİLİK VE HAYAT A.Ş.OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş.OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="FIH" label="FİBA EMEKLİLİK VE HAYAT A.Ş.OKS ATAK DEĞIŞKEN EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş.OKS ATAK DEĞIŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="FIV" label="FİBA EMEKLİLİK VE HAYAT A.Ş.OKS ATAK KATILIM DEĞİŞKEN  EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş.OKS ATAK KATILIM DEĞİŞKEN  EMEKLİLİK YATIRIM FONU </option> 
<option value="FIG" label="FİBA EMEKLİLİK VE HAYAT A.Ş.OKS DENGELI DEĞIŞKEN EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş.OKS DENGELI DEĞIŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="FIZ" label="FİBA EMEKLİLİK VE HAYAT A.Ş.OKS MUHAFAZAKAR DEĞIŞKEN EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT A.Ş.OKS MUHAFAZAKAR DEĞIŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="FGH" label="FİBA EMEKLİLİK VE HAYAT OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU"> FİBA EMEKLİLİK VE HAYAT OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="GEF" label="GARANTİ EMEKLİLİK  VE HAYAT A.Ş. DENGELİ DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU"> GARANTİ EMEKLİLİK  VE HAYAT A.Ş. DENGELİ DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="GEU" label="GARANTİ EMEKLİLİK HAYAT A.Ş. DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> GARANTİ EMEKLİLİK HAYAT A.Ş. DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="GHA" label="GARANTİ EMEKLİLİK VE HAYAT A.Ş. ALTIN EMEKLİLİK YATIRIM FONU"> GARANTİ EMEKLİLİK VE HAYAT A.Ş. ALTIN EMEKLİLİK YATIRIM FONU </option> 
<option value="GCV" label="GARANTİ EMEKLİLİK VE HAYAT A.Ş. BAŞLANGIÇ EMEKLİLİK YATIRIM FONU"> GARANTİ EMEKLİLİK VE HAYAT A.Ş. BAŞLANGIÇ EMEKLİLİK YATIRIM FONU </option> 
<option value="GDV" label="GARANTİ EMEKLİLİK VE HAYAT A.Ş. BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU"> GARANTİ EMEKLİLİK VE HAYAT A.Ş. BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU </option> 
<option value="GEK" label="GARANTİ EMEKLİLİK VE HAYAT A.Ş. BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"> GARANTİ EMEKLİLİK VE HAYAT A.Ş. BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU </option> 
<option value="GHF" label="GARANTİ EMEKLİLİK VE HAYAT A.Ş. BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU"> GARANTİ EMEKLİLİK VE HAYAT A.Ş. BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="GHE" label="GARANTİ EMEKLİLİK VE HAYAT A.Ş. DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> GARANTİ EMEKLİLİK VE HAYAT A.Ş. DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="GHT" label="GARANTİ EMEKLİLİK VE HAYAT A.Ş. DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> GARANTİ EMEKLİLİK VE HAYAT A.Ş. DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="GEH" label="GARANTİ EMEKLİLİK VE HAYAT A.Ş. HİSSE SENEDİ EMEKLİLİK YATIRIM FONU"> GARANTİ EMEKLİLİK VE HAYAT A.Ş. HİSSE SENEDİ EMEKLİLİK YATIRIM FONU </option> 
<option value="GEG" label="GARANTİ EMEKLİLİK VE HAYAT A.Ş. HİSSE SENEDİ GRUP EMEKLİLİK YATIRIM FONU"> GARANTİ EMEKLİLİK VE HAYAT A.Ş. HİSSE SENEDİ GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="GEA" label="GARANTİ EMEKLİLİK VE HAYAT A.Ş. KATILIM DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> GARANTİ EMEKLİLİK VE HAYAT A.Ş. KATILIM DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="GHL" label="GARANTİ EMEKLİLİK VE HAYAT A.Ş. KATILIM KATKI EMEKLİLİK YATIRIM FONU"> GARANTİ EMEKLİLİK VE HAYAT A.Ş. KATILIM KATKI EMEKLİLİK YATIRIM FONU </option> 
<option value="GES" label="GARANTİ EMEKLİLİK VE HAYAT A.Ş. KATILIM STANDART EMEKLİLİK YATIRIM FONU"> GARANTİ EMEKLİLİK VE HAYAT A.Ş. KATILIM STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="GHJ" label="GARANTİ EMEKLİLİK VE HAYAT A.Ş. OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> GARANTİ EMEKLİLİK VE HAYAT A.Ş. OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="GHU" label="GARANTİ EMEKLİLİK VE HAYAT A.Ş. OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> GARANTİ EMEKLİLİK VE HAYAT A.Ş. OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="GHN" label="GARANTİ EMEKLİLİK VE HAYAT A.Ş. OKS DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> GARANTİ EMEKLİLİK VE HAYAT A.Ş. OKS DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="GHV" label="GARANTİ EMEKLİLİK VE HAYAT A.Ş. OKS DENGELİ KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> GARANTİ EMEKLİLİK VE HAYAT A.Ş. OKS DENGELİ KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="GHM" label="GARANTİ EMEKLİLİK VE HAYAT A.Ş. OKS DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> GARANTİ EMEKLİLİK VE HAYAT A.Ş. OKS DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="GHY" label="GARANTİ EMEKLİLİK VE HAYAT A.Ş. OKS DİNAMİK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> GARANTİ EMEKLİLİK VE HAYAT A.Ş. OKS DİNAMİK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="GCK" label="GARANTİ EMEKLİLİK VE HAYAT A.Ş. OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU"> GARANTİ EMEKLİLİK VE HAYAT A.Ş. OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="GCS" label="GARANTİ EMEKLİLİK VE HAYAT A.Ş. OKS STANDART EMEKLİLİK YATIRIM FONU"> GARANTİ EMEKLİLİK VE HAYAT A.Ş. OKS STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="GHP" label="GARANTİ EMEKLİLİK VE HAYAT A.Ş. OKS TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> GARANTİ EMEKLİLİK VE HAYAT A.Ş. OKS TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="GHZ" label="GARANTİ EMEKLİLİK VE HAYAT A.Ş. OKS TEMKİNLİ KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> GARANTİ EMEKLİLİK VE HAYAT A.Ş. OKS TEMKİNLİ KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="GEL" label="GARANTİ EMEKLİLİK VE HAYAT A.Ş. PARA PİYASASI EMEKLİLİK YATIRIM FONU"> GARANTİ EMEKLİLİK VE HAYAT A.Ş. PARA PİYASASI EMEKLİLİK YATIRIM FONU </option> 
<option value="GHH" label="GARANTİ EMEKLİLİK VE HAYAT A.Ş. SÜRDÜRÜLEBİLİRLİK HİSSE SENEDİ EMEKLİLİK YATIRIM FONU"> GARANTİ EMEKLİLİK VE HAYAT A.Ş. SÜRDÜRÜLEBİLİRLİK HİSSE SENEDİ EMEKLİLİK YATIRIM FONU </option> 
<option value="GED" label="GARANTİ EMEKLİLİK VE HAYAT A.Ş. TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> GARANTİ EMEKLİLİK VE HAYAT A.Ş. TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="GKB" label="GARANTİ EMEKLİLİK VE HAYAT A.Ş. UZUN VADELİ KAMU BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"> GARANTİ EMEKLİLİK VE HAYAT A.Ş. UZUN VADELİ KAMU BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU </option> 
<option value="GHO" label="GARANTİ EMEKLİLİK VE HAYAT A.Ş. ÖZEL SEKTÖR BORÇLANMA ARAÇLARI EMEKLİLİK YAT.FONU"> GARANTİ EMEKLİLİK VE HAYAT A.Ş. ÖZEL SEKTÖR BORÇLANMA ARAÇLARI EMEKLİLİK YAT.FONU </option> 
<option value="GHG" label="GARANTİ EMEKLİLİK VE HAYAT A.Ş.DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"> GARANTİ EMEKLİLİK VE HAYAT A.Ş.DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU </option> 
<option value="GHK" label="GARANTİ EMEKLİLİK VE HAYAT A.Ş.DIŞ BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU"> GARANTİ EMEKLİLİK VE HAYAT A.Ş.DIŞ BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="GHI" label="GARANTİ EMEKLİLİK VE HAYAT A.Ş.KATKI EMEKLİLİK YATIRIM FONU"> GARANTİ EMEKLİLİK VE HAYAT A.Ş.KATKI EMEKLİLİK YATIRIM FONU </option> 
<option value="GHD" label="GARANTİ EMEKLİLİK VE HAYAT A.Ş.STANDART EMEKLİLİK YAT.FONU"> GARANTİ EMEKLİLİK VE HAYAT A.Ş.STANDART EMEKLİLİK YAT.FONU </option> 
<option value="HHF" label="HALK HAYAT VE EMEKLİLİK A.Ş. ALTIN KATILIM EMEKLİLİK YATIRIM FONU"> HALK HAYAT VE EMEKLİLİK A.Ş. ALTIN KATILIM EMEKLİLİK YATIRIM FONU </option> 
<option value="HHR" label="HALK HAYAT VE EMEKLİLİK A.Ş. BAŞLANGIÇ EMEKLİLİK YATIRIM FONU"> HALK HAYAT VE EMEKLİLİK A.Ş. BAŞLANGIÇ EMEKLİLİK YATIRIM FONU </option> 
<option value="HHV" label="HALK HAYAT VE EMEKLİLİK A.Ş. BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU"> HALK HAYAT VE EMEKLİLİK A.Ş. BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU </option> 
<option value="HHE" label="HALK HAYAT VE EMEKLİLİK A.Ş. DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> HALK HAYAT VE EMEKLİLİK A.Ş. DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="HHB" label="HALK HAYAT VE EMEKLİLİK A.Ş. HİSSE SENEDİ EMEKLİLİK YATIRIM FONU"> HALK HAYAT VE EMEKLİLİK A.Ş. HİSSE SENEDİ EMEKLİLİK YATIRIM FONU </option> 
<option value="HHK" label="HALK HAYAT VE EMEKLİLİK A.Ş. KAMU BORÇLANMA ARAÇLARI STANDART EMEKLİLİK YATIRIM FONU"> HALK HAYAT VE EMEKLİLİK A.Ş. KAMU BORÇLANMA ARAÇLARI STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="HHG" label="HALK HAYAT VE EMEKLİLİK A.Ş. KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"> HALK HAYAT VE EMEKLİLİK A.Ş. KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU </option> 
<option value="HHN" label="HALK HAYAT VE EMEKLİLİK A.Ş. KATILIM DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> HALK HAYAT VE EMEKLİLİK A.Ş. KATILIM DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="HHA" label="HALK HAYAT VE EMEKLİLİK A.Ş. KATILIM KATKI EMEKLİLİK YATIRIM FONU"> HALK HAYAT VE EMEKLİLİK A.Ş. KATILIM KATKI EMEKLİLİK YATIRIM FONU </option> 
<option value="HHT" label="HALK HAYAT VE EMEKLİLİK A.Ş. KATKI EMEKLİLİK YATIRIM FONU"> HALK HAYAT VE EMEKLİLİK A.Ş. KATKI EMEKLİLİK YATIRIM FONU </option> 
<option value="HEU" label="HALK HAYAT VE EMEKLİLİK A.Ş. OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU"> HALK HAYAT VE EMEKLİLİK A.Ş. OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="HEN" label="HALK HAYAT VE EMEKLİLİK A.Ş. OKS STANDART EMEKLİLİK YATIRIM FONU"> HALK HAYAT VE EMEKLİLİK A.Ş. OKS STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="HHP" label="HALK HAYAT VE EMEKLİLİK A.Ş. PARA PİYASASI EMEKLİLİK YATIRIM FONU"> HALK HAYAT VE EMEKLİLİK A.Ş. PARA PİYASASI EMEKLİLİK YATIRIM FONU </option> 
<option value="HHY" label="HALK HAYAT VE EMEKLİLİK A.Ş. TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> HALK HAYAT VE EMEKLİLİK A.Ş. TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="HHL" label="HALK HAYAT VE EMEKLİLİK A.Ş.EMANET PARA PİYASASI EMEKLİLİK YATIRIM FONU"> HALK HAYAT VE EMEKLİLİK A.Ş.EMANET PARA PİYASASI EMEKLİLİK YATIRIM FONU </option> 
<option value="HHM" label="HALK HAYAT VE EMEKLİLİK A.Ş.KATILIM HİSSE SENEDİ E.Y.F"> HALK HAYAT VE EMEKLİLİK A.Ş.KATILIM HİSSE SENEDİ E.Y.F </option> 
<option value="HHD" label="HALK HAYAT VE EMEKLİLİK A.Ş.KATILIM STANDART EMEK.Y.F."> HALK HAYAT VE EMEKLİLİK A.Ş.KATILIM STANDART EMEK.Y.F. </option> 
<option value="HHO" label="HALK HAYAT VE EMEKLİLİK A.Ş.OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> HALK HAYAT VE EMEKLİLİK A.Ş.OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="HHI" label="HALK HAYAT VE EMEKLİLİK A.Ş.OKS ATAK DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> HALK HAYAT VE EMEKLİLİK A.Ş.OKS ATAK DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="HHU" label="HALK HAYAT VE EMEKLİLİK A.Ş.OKS ATAK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> HALK HAYAT VE EMEKLİLİK A.Ş.OKS ATAK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="HHH" label="HALK HAYAT VE EMEKLİLİK A.Ş.OKS DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> HALK HAYAT VE EMEKLİLİK A.Ş.OKS DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="HHC" label="HALK HAYAT VE EMEKLİLİK A.Ş.OKS TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> HALK HAYAT VE EMEKLİLİK A.Ş.OKS TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="HHZ" label="HALK HAYAT VE EMEKİLİK A.Ş. OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> HALK HAYAT VE EMEKİLİK A.Ş. OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="KES" label="KATILIM EMEKLİLİK VE HAYAT A.Ş. AGRESİF KATILIM DEĞİŞKEN ( DÖVİZ )EMEKLİLİK YATIRIM FONU"> KATILIM EMEKLİLİK VE HAYAT A.Ş. AGRESİF KATILIM DEĞİŞKEN ( DÖVİZ )EMEKLİLİK YATIRIM FONU </option> 
<option value="KEF" label="KATILIM EMEKLİLİK VE HAYAT A.Ş. ALTIN KATILIM EMEKLİLİK YATIRIM FONU"> KATILIM EMEKLİLİK VE HAYAT A.Ş. ALTIN KATILIM EMEKLİLİK YATIRIM FONU </option> 
<option value="KEY" label="KATILIM EMEKLİLİK VE HAYAT A.Ş. BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU"> KATILIM EMEKLİLİK VE HAYAT A.Ş. BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU </option> 
<option value="KEG" label="KATILIM EMEKLİLİK VE HAYAT A.Ş. DENGELİ KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> KATILIM EMEKLİLİK VE HAYAT A.Ş. DENGELİ KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="KKS" label="KATILIM EMEKLİLİK VE HAYAT A.Ş. KAMU KİRA SERTİFİKALARI KATILIM EMEKLİLİK YATIRIM FONU"> KATILIM EMEKLİLİK VE HAYAT A.Ş. KAMU KİRA SERTİFİKALARI KATILIM EMEKLİLİK YATIRIM FONU </option> 
<option value="KEK" label="KATILIM EMEKLİLİK VE HAYAT A.Ş. KATILIM DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU"> KATILIM EMEKLİLİK VE HAYAT A.Ş. KATILIM DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="KEH" label="KATILIM EMEKLİLİK VE HAYAT A.Ş. KATILIM HİSSE SENEDİ EMEKLİLİK YATIRIM FONU"> KATILIM EMEKLİLİK VE HAYAT A.Ş. KATILIM HİSSE SENEDİ EMEKLİLİK YATIRIM FONU </option> 
<option value="KEA" label="KATILIM EMEKLİLİK VE HAYAT A.Ş. KATILIM KATKI EMEKLİLİK YATIRIM FONU"> KATILIM EMEKLİLİK VE HAYAT A.Ş. KATILIM KATKI EMEKLİLİK YATIRIM FONU </option> 
<option value="KEB" label="KATILIM EMEKLİLİK VE HAYAT A.Ş. KATILIM STANDART EMEKLİLİK YATIRIM FONU"> KATILIM EMEKLİLİK VE HAYAT A.Ş. KATILIM STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="KEZ" label="KATILIM EMEKLİLİK VE HAYAT A.Ş. OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> KATILIM EMEKLİLİK VE HAYAT A.Ş. OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="KET" label="KATILIM EMEKLİLİK VE HAYAT A.Ş. OKS ATAK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> KATILIM EMEKLİLİK VE HAYAT A.Ş. OKS ATAK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="KTZ" label="KATILIM EMEKLİLİK VE HAYAT A.Ş. OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU"> KATILIM EMEKLİLİK VE HAYAT A.Ş. OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="MHL" label="METLIFE EMEKLİLİK VE HAYAT A.Ş. PARA PİYASASI EMEKLİLİK YATIRIM FONU"> METLIFE EMEKLİLİK VE HAYAT A.Ş. PARA PİYASASI EMEKLİLİK YATIRIM FONU </option> 
<option value="MHH" label="METLİFE EMEKLİLK VE HAYAT A.Ş.HİSSE SENEDİ EMEKLİLİK YATIRIM FONU"> METLİFE EMEKLİLK VE HAYAT A.Ş.HİSSE SENEDİ EMEKLİLİK YATIRIM FONU </option> 
<option value="MHC" label="METLİFE EMEKLİLİK VE HAYAT A.Ş. BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU"> METLİFE EMEKLİLİK VE HAYAT A.Ş. BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU </option> 
<option value="MHD" label="METLİFE EMEKLİLİK VE HAYAT A.Ş. KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FO"> METLİFE EMEKLİLİK VE HAYAT A.Ş. KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FO </option> 
<option value="MHT" label="METLİFE EMEKLİLİK VE HAYAT A.Ş. KATKI EMEKLİLİK YATIRIM FONU"> METLİFE EMEKLİLİK VE HAYAT A.Ş. KATKI EMEKLİLİK YATIRIM FONU </option> 
<option value="MHR" label="METLİFE EMEKLİLİK VE HAYAT A.Ş. OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> METLİFE EMEKLİLİK VE HAYAT A.Ş. OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="MHV" label="METLİFE EMEKLİLİK VE HAYAT A.Ş. OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> METLİFE EMEKLİLİK VE HAYAT A.Ş. OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="MHO" label="METLİFE EMEKLİLİK VE HAYAT A.Ş. OKS ATAK DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> METLİFE EMEKLİLİK VE HAYAT A.Ş. OKS ATAK DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="MHU" label="METLİFE EMEKLİLİK VE HAYAT A.Ş. OKS ATAK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> METLİFE EMEKLİLİK VE HAYAT A.Ş. OKS ATAK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="MHN" label="METLİFE EMEKLİLİK VE HAYAT A.Ş. OKS DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> METLİFE EMEKLİLİK VE HAYAT A.Ş. OKS DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="MHI" label="METLİFE EMEKLİLİK VE HAYAT A.Ş. OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU"> METLİFE EMEKLİLİK VE HAYAT A.Ş. OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="MHZ" label="METLİFE EMEKLİLİK VE HAYAT A.Ş. OKS STANDART EMEKLİLİK YATIRIM FONU"> METLİFE EMEKLİLİK VE HAYAT A.Ş. OKS STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="MHM" label="METLİFE EMEKLİLİK VE HAYAT A.Ş. OKS TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> METLİFE EMEKLİLİK VE HAYAT A.Ş. OKS TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="MHB" label="METLİFE EMEKLİLİK VE HAYAT A.Ş.BAŞLANGIÇ EMEKLİLİK YATIRIM FONU"> METLİFE EMEKLİLİK VE HAYAT A.Ş.BAŞLANGIÇ EMEKLİLİK YATIRIM FONU </option> 
<option value="MHE" label="METLİFE EMEKLİLİK VE HAYAT A.Ş.DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> METLİFE EMEKLİLİK VE HAYAT A.Ş.DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="MHY" label="METLİFE EMEKLİLİK VE HAYAT A.Ş.DENGELİ DEĞİŞKEN GRUP EMEKLİKLİK YATIRIM FONU"> METLİFE EMEKLİLİK VE HAYAT A.Ş.DENGELİ DEĞİŞKEN GRUP EMEKLİKLİK YATIRIM FONU </option> 
<option value="MHG" label="METLİFE EMEKLİLİK VE HAYAT A.Ş.KAMU BORÇLANMA  ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU"> METLİFE EMEKLİLİK VE HAYAT A.Ş.KAMU BORÇLANMA  ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="MHK" label="METLİFE EMEKLİLİK VE HAYAT A.Ş.KAMU BORÇLANMA ARAÇLARI STANDART EMEKLİLİK YATIRIM FONU"> METLİFE EMEKLİLİK VE HAYAT A.Ş.KAMU BORÇLANMA ARAÇLARI STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="MHA" label="METLİFE EMEKLİLİK VE HAYAT A.Ş.KATILIM KATKI EMEKLİLİK YATIRIM FONU"> METLİFE EMEKLİLİK VE HAYAT A.Ş.KATILIM KATKI EMEKLİLİK YATIRIM FONU </option> 
<option value="MHS" label="METLİFE EMEKLİLİK VE HAYAT A.Ş.KATILIM STANDART EMEKLİLİK YATIRIM FONU"> METLİFE EMEKLİLİK VE HAYAT A.Ş.KATILIM STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="IER" label="NN HAYAT  VE EMEKLİLİK A.Ş. PARA PİYASASI EMEKLİLİK YATIRIM FONU"> NN HAYAT  VE EMEKLİLİK A.Ş. PARA PİYASASI EMEKLİLİK YATIRIM FONU </option> 
<option value="NHR" label="NN HAYAT VE EMEKLILIK A.Ş. OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU"> NN HAYAT VE EMEKLILIK A.Ş. OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="NHN" label="NN HAYAT VE EMEKLİLİK A.Ş. AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> NN HAYAT VE EMEKLİLİK A.Ş. AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="NHA" label="NN HAYAT VE EMEKLİLİK A.Ş. ALTIN EMEKLİLİK YATIRIM FONU"> NN HAYAT VE EMEKLİLİK A.Ş. ALTIN EMEKLİLİK YATIRIM FONU </option> 
<option value="NHB" label="NN HAYAT VE EMEKLİLİK A.Ş. BAŞLANGIÇ EMEKLİLİK YATIRIM FONU"> NN HAYAT VE EMEKLİLİK A.Ş. BAŞLANGIÇ EMEKLİLİK YATIRIM FONU </option> 
<option value="NHK" label="NN HAYAT VE EMEKLİLİK A.Ş. BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU"> NN HAYAT VE EMEKLİLİK A.Ş. BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU </option> 
<option value="IEG" label="NN HAYAT VE EMEKLİLİK A.Ş. BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"> NN HAYAT VE EMEKLİLİK A.Ş. BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU </option> 
<option value="IEE" label="NN HAYAT VE EMEKLİLİK A.Ş. DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> NN HAYAT VE EMEKLİLİK A.Ş. DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="IEA" label="NN HAYAT VE EMEKLİLİK A.Ş. DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> NN HAYAT VE EMEKLİLİK A.Ş. DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="IEF" label="NN HAYAT VE EMEKLİLİK A.Ş. DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> NN HAYAT VE EMEKLİLİK A.Ş. DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="IEH" label="NN HAYAT VE EMEKLİLİK A.Ş. HİSSE SENEDİ EMEKLİLİK YATIRIM FONU"> NN HAYAT VE EMEKLİLİK A.Ş. HİSSE SENEDİ EMEKLİLİK YATIRIM FONU </option> 
<option value="IEK" label="NN HAYAT VE EMEKLİLİK A.Ş. KARMA EMEKLİLİK YATIRIM FONU"> NN HAYAT VE EMEKLİLİK A.Ş. KARMA EMEKLİLİK YATIRIM FONU </option> 
<option value="IGE" label="NN HAYAT VE EMEKLİLİK A.Ş. KATKI EMEKLİLİK YATIRIM FONU"> NN HAYAT VE EMEKLİLİK A.Ş. KATKI EMEKLİLİK YATIRIM FONU </option> 
<option value="NHO" label="NN HAYAT VE EMEKLİLİK A.Ş. OKS STANDART EMEKLİLİK YATIRIM FONU"> NN HAYAT VE EMEKLİLİK A.Ş. OKS STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="IEB" label="NN HAYAT VE EMEKLİLİK A.Ş.KAMU BORÇLANMA ARAÇ.STANDART EMEK.YATIRIM FONU"> NN HAYAT VE EMEKLİLİK A.Ş.KAMU BORÇLANMA ARAÇ.STANDART EMEK.YATIRIM FONU </option> 
<option value="NHG" label="NN HAYAT VE EMEKLİLİK A.Ş.OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> NN HAYAT VE EMEKLİLİK A.Ş.OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="NHC" label="NN HAYAT VE EMEKLİLİK A.Ş.OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> NN HAYAT VE EMEKLİLİK A.Ş.OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="NHI" label="NN HAYAT VE EMEKLİLİK A.Ş.OKS DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> NN HAYAT VE EMEKLİLİK A.Ş.OKS DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="NHL" label="NN HAYAT VE EMEKLİLİK A.Ş.OKS DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> NN HAYAT VE EMEKLİLİK A.Ş.OKS DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="NHH" label="NN HAYAT VE EMEKLİLİK A.Ş.OKS DİNAMİK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> NN HAYAT VE EMEKLİLİK A.Ş.OKS DİNAMİK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="NHF" label="NN HAYAT VE EMEKLİLİK A.Ş.OKSTEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> NN HAYAT VE EMEKLİLİK A.Ş.OKSTEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="NHM" label="NN HAYAT VE EMEKLİLİK A.Ş.QİNVEST PORTFÖY TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> NN HAYAT VE EMEKLİLİK A.Ş.QİNVEST PORTFÖY TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="VYB" label="VAKIF EMEKLILIK VE HAYAT A.Ş. KATILIM HISSE SENEDI EYF"> VAKIF EMEKLILIK VE HAYAT A.Ş. KATILIM HISSE SENEDI EYF </option> 
<option value="VGY" label="VAKIF EMEKLİLİK A.Ş. PERA 3 DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK A.Ş. PERA 3 DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="VEU" label="VAKIF EMEKLİLİK A.Ş. TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK A.Ş. TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="VGT" label="VAKIF EMEKLİLİK VE HAYAT  A.Ş.PERA 2 DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK VE HAYAT  A.Ş.PERA 2 DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="VGA" label="VAKIF EMEKLİLİK VE HAYAT A.Ş. ALTIN KATILIM EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK VE HAYAT A.Ş. ALTIN KATILIM EMEKLİLİK YATIRIM FONU </option> 
<option value="VKJ" label="VAKIF EMEKLİLİK VE HAYAT A.Ş. BAŞLANGIÇ EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK VE HAYAT A.Ş. BAŞLANGIÇ EMEKLİLİK YATIRIM FONU </option> 
<option value="VKE" label="VAKIF EMEKLİLİK VE HAYAT A.Ş. BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK VE HAYAT A.Ş. BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU </option> 
<option value="VEG" label="VAKIF EMEKLİLİK VE HAYAT A.Ş. BİRİNCİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK VE HAYAT A.Ş. BİRİNCİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="VGD" label="VAKIF EMEKLİLİK VE HAYAT A.Ş. BİRİNCİ KAMU BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK VE HAYAT A.Ş. BİRİNCİ KAMU BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="VES" label="VAKIF EMEKLİLİK VE HAYAT A.Ş. DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK VE HAYAT A.Ş. DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="VEE" label="VAKIF EMEKLİLİK VE HAYAT A.Ş. DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK VE HAYAT A.Ş. DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="VGE" label="VAKIF EMEKLİLİK VE HAYAT A.Ş. DİNAMİK DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK VE HAYAT A.Ş. DİNAMİK DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="VEH" label="VAKIF EMEKLİLİK VE HAYAT A.Ş. HİSSE SENEDİ EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK VE HAYAT A.Ş. HİSSE SENEDİ EMEKLİLİK YATIRIM FONU </option> 
<option value="VET" label="VAKIF EMEKLİLİK VE HAYAT A.Ş. KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK VE HAYAT A.Ş. KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU </option> 
<option value="VEB" label="VAKIF EMEKLİLİK VE HAYAT A.Ş. KATILIM DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK VE HAYAT A.Ş. KATILIM DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="VEA" label="VAKIF EMEKLİLİK VE HAYAT A.Ş. KATILIM DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK VE HAYAT A.Ş. KATILIM DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="VEY" label="VAKIF EMEKLİLİK VE HAYAT A.Ş. KATILIM DİNAMİK DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK VE HAYAT A.Ş. KATILIM DİNAMİK DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="VER" label="VAKIF EMEKLİLİK VE HAYAT A.Ş. KATILIM KATKI EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK VE HAYAT A.Ş. KATILIM KATKI EMEKLİLİK YATIRIM FONU </option> 
<option value="VGB" label="VAKIF EMEKLİLİK VE HAYAT A.Ş. KATILIM STANDART EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK VE HAYAT A.Ş. KATILIM STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="VEI" label="VAKIF EMEKLİLİK VE HAYAT A.Ş. KATKI EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK VE HAYAT A.Ş. KATKI EMEKLİLİK YATIRIM FONU </option> 
<option value="VGF" label="VAKIF EMEKLİLİK VE HAYAT A.Ş. OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK VE HAYAT A.Ş. OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="VEO" label="VAKIF EMEKLİLİK VE HAYAT A.Ş. OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK VE HAYAT A.Ş. OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="VGH" label="VAKIF EMEKLİLİK VE HAYAT A.Ş. OKS ATAK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK VE HAYAT A.Ş. OKS ATAK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="VEV" label="VAKIF EMEKLİLİK VE HAYAT A.Ş. OKS DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK VE HAYAT A.Ş. OKS DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="VGG" label="VAKIF EMEKLİLİK VE HAYAT A.Ş. OKS DENGELİ KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK VE HAYAT A.Ş. OKS DENGELİ KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="VGC" label="VAKIF EMEKLİLİK VE HAYAT A.Ş. OKS DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK VE HAYAT A.Ş. OKS DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="VGK" label="VAKIF EMEKLİLİK VE HAYAT A.Ş. OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK VE HAYAT A.Ş. OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="VED" label="VAKIF EMEKLİLİK VE HAYAT A.Ş. OKS MUHAFAZAKAR KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK VE HAYAT A.Ş. OKS MUHAFAZAKAR KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="VGZ" label="VAKIF EMEKLİLİK VE HAYAT A.Ş. OKS STANDART EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK VE HAYAT A.Ş. OKS STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="VEP" label="VAKIF EMEKLİLİK VE HAYAT A.Ş. OKS TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK VE HAYAT A.Ş. OKS TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="VEL" label="VAKIF EMEKLİLİK VE HAYAT A.Ş. PARA PİYASASI EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK VE HAYAT A.Ş. PARA PİYASASI EMEKLİLİK YATIRIM FONU </option> 
<option value="VGL" label="VAKIF EMEKLİLİK VE HAYAT A.Ş. PARA PİYASASI GRUP  EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK VE HAYAT A.Ş. PARA PİYASASI GRUP  EMEKLİLİK YATIRIM FONU </option> 
<option value="VGP" label="VAKIF EMEKLİLİK VE HAYAT A.Ş. PERA 1 DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK VE HAYAT A.Ş. PERA 1 DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="VEK" label="VAKIF EMEKLİLİK VE HAYAT A.Ş. STANDART EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK VE HAYAT A.Ş. STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="VEC" label="VAKIF EMEKLİLİK VE HAYAT A.Ş. İKİNCİ KAMU BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU"> VAKIF EMEKLİLİK VE HAYAT A.Ş. İKİNCİ KAMU BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU </option> 
<option value="ZHN" label="ZİRAAT HAYAT VE EMEKLİLİK A.Ş. ALTIN KATILIM EMEKLİLİK YATIRIM FONU"> ZİRAAT HAYAT VE EMEKLİLİK A.Ş. ALTIN KATILIM EMEKLİLİK YATIRIM FONU </option> 
<option value="ZEB" label="ZİRAAT HAYAT VE EMEKLİLİK A.Ş. BAŞLANGIÇ EMEKLİLİK YATIRIM FONU"> ZİRAAT HAYAT VE EMEKLİLİK A.Ş. BAŞLANGIÇ EMEKLİLİK YATIRIM FONU </option> 
<option value="ZEK" label="ZİRAAT HAYAT VE EMEKLİLİK A.Ş. BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU"> ZİRAAT HAYAT VE EMEKLİLİK A.Ş. BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU </option> 
<option value="ZHE" label="ZİRAAT HAYAT VE EMEKLİLİK A.Ş. DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> ZİRAAT HAYAT VE EMEKLİLİK A.Ş. DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="ZHB" label="ZİRAAT HAYAT VE EMEKLİLİK A.Ş. HİSSE SENEDİ EMEKLİLİK YATIRIM FONU"> ZİRAAT HAYAT VE EMEKLİLİK A.Ş. HİSSE SENEDİ EMEKLİLİK YATIRIM FONU </option> 
<option value="ZHG" label="ZİRAAT HAYAT VE EMEKLİLİK A.Ş. KAMU BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"> ZİRAAT HAYAT VE EMEKLİLİK A.Ş. KAMU BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU </option> 
<option value="ZHD" label="ZİRAAT HAYAT VE EMEKLİLİK A.Ş. KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU"> ZİRAAT HAYAT VE EMEKLİLİK A.Ş. KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU </option> 
<option value="ZHF" label="ZİRAAT HAYAT VE EMEKLİLİK A.Ş. KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> ZİRAAT HAYAT VE EMEKLİLİK A.Ş. KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="ZHT" label="ZİRAAT HAYAT VE EMEKLİLİK A.Ş. KATILIM KATKI EMEKLİLİK YAT.FONU"> ZİRAAT HAYAT VE EMEKLİLİK A.Ş. KATILIM KATKI EMEKLİLİK YAT.FONU </option> 
<option value="ZHA" label="ZİRAAT HAYAT VE EMEKLİLİK A.Ş. KATILIM STANDART EMEKLİLİK YATIRIM FONU"> ZİRAAT HAYAT VE EMEKLİLİK A.Ş. KATILIM STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="ZHK" label="ZİRAAT HAYAT VE EMEKLİLİK A.Ş. KATKI EMEKLİLİK YAT.FONU"> ZİRAAT HAYAT VE EMEKLİLİK A.Ş. KATKI EMEKLİLİK YAT.FONU </option> 
<option value="ZHI" label="ZİRAAT HAYAT VE EMEKLİLİK A.Ş. OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU"> ZİRAAT HAYAT VE EMEKLİLİK A.Ş. OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="ZHC" label="ZİRAAT HAYAT VE EMEKLİLİK A.Ş. OKS STANDART EMEKLİLİK YATIRIM FONU"> ZİRAAT HAYAT VE EMEKLİLİK A.Ş. OKS STANDART EMEKLİLİK YATIRIM FONU </option> 
<option value="ZHR" label="ZİRAAT HAYAT VE EMEKLİLİK A.Ş. PARA PİYASASI EMEKLİLİK YATIRIM FONU"> ZİRAAT HAYAT VE EMEKLİLİK A.Ş. PARA PİYASASI EMEKLİLİK YATIRIM FONU </option> 
<option value="ZHM" label="ZİRAAT HAYAT VE EMEKLİLİK A.Ş.OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> ZİRAAT HAYAT VE EMEKLİLİK A.Ş.OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="ZHP" label="ZİRAAT HAYAT VE EMEKLİLİK A.Ş.OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> ZİRAAT HAYAT VE EMEKLİLİK A.Ş.OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="ZHU" label="ZİRAAT HAYAT VE EMEKLİLİK A.Ş.OKS ATAK DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> ZİRAAT HAYAT VE EMEKLİLİK A.Ş.OKS ATAK DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="ZHV" label="ZİRAAT HAYAT VE EMEKLİLİK A.Ş.OKS ATAK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> ZİRAAT HAYAT VE EMEKLİLİK A.Ş.OKS ATAK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="ZHY" label="ZİRAAT HAYAT VE EMEKLİLİK A.Ş.OKS DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> ZİRAAT HAYAT VE EMEKLİLİK A.Ş.OKS DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="ZHZ" label="ZİRAAT HAYAT VE EMEKLİLİK A.Ş.OKS TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU"> ZİRAAT HAYAT VE EMEKLİLİK A.Ş.OKS TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU </option> 
<option value="ZHS" label="ZİRAAT HAYAT VE EMEKLİLİK A.Ş.STANDART EMEKLİLİK YAT.FONU"> ZİRAAT HAYAT VE EMEKLİLİK A.Ş.STANDART EMEKLİLİK YAT.FONU </option> 

 </datalist> 

`
